Fix CI
This commit fixes workflows.

TICO-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

diff --git a/.github/workflows/check-pr.yaml b/.github/workflows/check-pr.yaml
--- a/.github/workflows/check-pr.yaml
+++ b/.github/workflows/check-pr.yaml
@@ -1,5 +1,4 @@
 name: Check PR
-description: Checks pull requests by verifying code format, building the project, and running unit tests.
 
 on:
   pull_request:
@@ -39,25 +38,43 @@ jobs:
         id: os
         run: |
           CODENAME=$(lsb_release -cs)
-          echo "codename=$CODENAME" >> $GITHUB_OUTPUT
+          echo "codename=$CODENAME" >> "$GITHUB_OUTPUT"
 
-      - name: Download one-compiler package
-        id: download
-        uses: ./.github/actions/download-release-asset
-        with:
-          owner: Samsung
-          repo: ONE
-          tag: 1.29.0
-          package: one-compiler-${{ steps.os.outputs.codename }}_1.29.0_amd64.deb
+      # TODO Enable this step after one-compiler 1.30.0 release.
+      # - name: Download one-compiler package
+      #   id: download
+      #   uses: ./.github/actions/download-release-asset
+      #   with:
+      #     owner: Samsung
+      #     repo: ONE
+      #     tag: 1.30.0
+      #     filename: one-compiler-${{ steps.os.outputs.codename }}_1.30.0_amd64.deb
+      # - name: "Install one-compiler"
+      #   run: |
+      #     sudo dpkg -i ${{ steps.download.outputs.filename }}
+      #     sudo apt-get install -f -y
+      #     onecc --version
 
-      - name: "Install one-compiler"
+      - name: Download issue attatchment (one-compiler latest)
         run: |
-          dpkg -i ${{ steps.download.outputs.filename }}
-          apt-get install -f -y
-          onecc --version
+          curl -L -o one-compiler-latest.zip \
+            "https://github.com/user-attachments/files/19561702/one-compiler_1.30.0.25040116_amd64.zip"
+
+      - name: Unzip and install the one-compiler package
+        run: |
+          unzip one-compiler-latest.zip -d one-compiler-package
+          ls -l one-compiler-package
+
+          sudo dpkg -i one-compiler-package/*.deb
+          sudo apt-get install -f -y # fix dependencies if needed
+
+      - name: Check installation
+        run: |
+          onecc --version || echo "Installation failed."
 
       - name: "Build package"
         run: |
+          pip install setuptools
           ./ccex build
 
       - name: "Run install"
@@ -86,5 +103,5 @@ jobs:
       - name: "Upload artifact"
         uses: actions/upload-artifact@v4
         with:
-          name: "wheel"
+          name: "wheel-${{ matrix.torch-version }}"
           path: "./dist/"
